# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: backend-pipelines

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    #    strategy:
    #      matrix:
    #        node-version: [20.13.1]
    #        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.13.1

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies
        run: |
          cd backend/
          echo "DATABASE_URL=$DATABASE_URL" >> .env
        
          npm ci

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/node_modules/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.13.1

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies
        run: |
          ls
          cd backend/
          npm install

      - name: Run tests with coverage
        run: |
          cd backend/
          npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/
  dockerize-and-push-dev:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: development
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:dev backend/
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/backend:dev ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:dev
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}

  sonarcloud-analysis:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Collect coverage (React-specific)
        run: |
          cd backend
          npm run test:ci -- --coverage
        env:
          CI: true

      - name: Upload coverage report
        run: |
          cp backend/coverage/lcov.info .

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.ORGANIZATION_KEY }} \
            -Dsonar.sources=./backend \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  dockerize-and-push-prod:
    needs: [test, sonarcloud-analysis]
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.ref == 'refs/heads/production' &&  github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Check SonarCloud Quality Gate
#        run: |
#          curl -u ${{ secrets.SONAR_TOKEN }}: \
#          "https://sonarcloud.io/api/project_badges/measure?project=${{ secrets.PROJECT_KEY }}&metric=alert_status" | grep -q "OK" || exit 1


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/backend:prod backend/
          docker tag ${{ secrets.DH_USERNAME }}/backend:prod ${{ secrets.DH_USERNAME }}/backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub4
        run: |
          docker push ${{ secrets.DH_USERNAME }}/backend:prod
          docker push ${{ secrets.DH_USERNAME }}/backend:${{ github.sha }}